name: Build
on: push

jobs:
  build:
    name: macOS
    runs-on: macos-latest
    env:
      SDL_VERSION: 2.0.14
      SDL_MIXER_VERSION: 2.0.4
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up environment
        run: |
          curl -o SDL2.dmg https://www.libsdl.org/release/SDL2-$SDL_VERSION.dmg
          curl -o SDL2_mixer.dmg https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-$SDL_MIXER_VERSION.dmg
          mkdir -p ~/Library/Frameworks
          VOLUME=$(hdiutil attach SDL2.dmg | grep -o '/Volumes/.*')
          echo "Installing framework:" "/Volumes/SDL2"/*.framework
          cp -rp "$VOLUME"/*.framework ~/Library/Frameworks
          hdiutil detach "$VOLUME"
          VOLUME=$(hdiutil attach SDL2_mixer.dmg | grep -o '/Volumes/.*')
          echo "Installing framework:" "/Volumes/SDL2"/*.framework
          cp -rp "$VOLUME"/*.framework ~/Library/Frameworks
          hdiutil detach "$VOLUME"
      - name: Build and test
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make
          echo "Library dependencies:"
          otool -L ~/Library/Frameworks/SDL2_mixer.framework/SDL2_mixer
          make install
          echo "Copied dependencies:"
          ls -l cmaketest.app/Contents/Frameworks
          echo "Fixed library dependencies:"
          otool -L cmaketest.app/Contents/Frameworks/SDL2_mixer.framework/SDL2_mixer
          echo "Creating disk image"
          hdiutil create -volname cmaketest -srcfolder cmaketest.app -ov -format UDZO cmaketest.dmg
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macOS
          path: build/cmaketest.dmg
